FROM ruby:2.3.1

# Installing ffmpeg
RUN echo 'deb http://ftp.uk.debian.org/debian jessie-backports main' >> /etc/apt/sources.list.d/backports.list \
 && apt-get update \
 && apt-get install -y ffmpeg \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /project

COPY backend-rails/Gemfile .
COPY backend-rails/Gemfile.lock .
RUN bundle install

COPY backend-rails .

ENV RAILS_ENV=production

EXPOSE 3000

CMD ["rails", "server"]
